# yaml-language-server: $schema=./node_modules/envio/.schema.json
name: indexer

contracts:
  - name: TokenLock
    handler: src/TokenLockHandlers.ts
    events:
      - event: "Claimed(address indexed owner, address indexed recipient, uint256 amount)"
      - event: "Locked(address indexed owner, uint256 chainId, uint256 poolId, address indexed recipientId, uint256 amount)"
        field_selection:
          block_fields:

  - name: MerkleAirdrop
    handler: src/MerkleAirdropHandlers.ts
    events:
      - event: "Claim(address indexed claimant, uint256 amount, uint256 chainId, uint256 poolId)"
      - event: "MerkleRootChanged(bytes32 merkleRoot)"
      - event: "OwnershipTransferred(address indexed previousOwner, address indexed newOwner)"
      - event: "Clawback(address indexed clawbackAddress, uint256 amount, address token)"

networks:
  - id: 11155111
    start_block: 0
    contracts:
      - name: TokenLock
        address:
          - 0x9324bC7A3aDFC19A40E790eCeFf9e46009df5587
          - 0x006384dE9D80C04bF908495676C507EFfF5C7AD2
      - name: MerkleAirdrop
        address:
          - 0xc234225833d40C3248ca672F7eFDF071B33A3870
          - 0x873a6D01eC613bb98A941E061D09c1FfD729B904
          - 0x76885b6918A8A26996030f5fbcf9B43e08EaD64D
  - id: 1
    start_block: 0
    contracts:
      - name: TokenLock
        address:
          - 0x73d7439ca441da0bed1020a1f1c88bd572f3d57c
