# yaml-language-server: $schema=./node_modules/envio/.schema.json
name: indexer

contracts:
  - name: TokenLock
    handler: src/TokenLockHandlers.ts
    events:
      - event: "Claimed(address indexed owner, address indexed recipient, uint256 amount)"
      - event: "Locked(address indexed owner, uint256 chainId, uint256 poolId, address indexed recipientId, uint256 amount)"
        field_selection:
          block_fields:

  - name: MerkleAirdrop
    handler: src/MerkleAirdropHandlers.ts
    events:
      - event: "Claim(address indexed claimant, uint256 amount, uint256 chainId, uint256 poolId)"
      - event: "MerkleRootChanged(bytes32 merkleRoot)"
      - event: "OwnershipTransferred(address indexed previousOwner, address indexed newOwner)"
      - event: "Clawback(address indexed clawbackAddress, uint256 amount, address token)"

networks:
  - id: 11155111
    start_block: 0
    contracts:
      - name: TokenLock
        address:
          - 0x9324bC7A3aDFC19A40E790eCeFf9e46009df5587
      - name: MerkleAirdrop
        address:
          - 0x50C6C30C1e7aa5f21735fFED67372E89B7Cf3919
